name: hola-mundo #Nombre del workflow
on: [push] #evento que lo activará
jobs: #Definición de los jobs
	hola-mundo: #Nombre del job
		runs-on: ubuntu-latest #Maquina en la que correrá
		steps: #Lista de steps del job hola-mundo
   			- name: Setup Java JDK
        			uses: actions/setup-java@v3.12.0
        				with: 
          					distribution: oracle
          					java-version: 17
          					java-package: jdk
        		- name: Checkout
        			uses: actions/checkout@v3
			- name: compila #Nombre del step
				run: javac HelloWorld.java
			- name: ejecuta #Segundo step de nombre Hola mundo
				run : java HelloWorld #bash
